// tests/applications/Applications-ResumeUploads.spec.js
// ---------------------------------------------------------------------------
// Module 10 — Applications  |  Resume / file-upload scenarios
//
//   🟢 Already covered by tests/candidates/candidates.spec.js:
//        TC_10_002 (Add button), TC_10_003/004 (email single/multi),
//        TC_10_007/008 (send now/later), TC_10_011 (DOCX upload)
//
//   🟡 Partially covered:
//        Resume upload flow → see TC_APP_001 below (re-implements the flow
//        in the dedicated Applications folder and extends it)
//
//   🔴 Covered here:
//        TC_APP_003  – Upload a PDF resume → candidate created
//        TC_APP_004  – Upload a DOC (.doc, NOT .docx) resume → candidate created
//        TC_APP_005  – Upload multiple resume files in one import → candidates created
//        TC_APP_006  – Upload a plain-text file (invalid) → rejected or no candidate created
//
// Fixtures (auto-generated by the setup script):
//   fixtures/resumes/John_Smith_DotNet_Resume.pdf
//   fixtures/resumes/John_Smith_DotNet_Resume.docx   (valid .docx — also used by TC_CAND_004)
//   fixtures/resumes/invalid_file.txt                 (plain text — not a resume)
//
// Pre-condition for every test in this file:
//   A published job exists whose title matches testData.candidates.jobTitle
//   ('.net developer').  The authFixture handles login + logout per test.
// ---------------------------------------------------------------------------

const { test, expect }           = require('../../utils/authFixture');
const { CandidatesPage }         = require('../../pages/CandidatesPage');
const testData                   = require('../../data/testData.json');
const path                       = require('path');

const FIX = path.resolve(__dirname, '../../', 'fixtures');
const PD  = path.join(FIX, 'resumes');

// ─── shared helpers ──────────────────────────────────────────────────────

/** Opens the Candidates view for the default test job and returns the URL + initial count. */
async function openCandidates(candidatesPage) {
  const jobTitle = testData.candidates.jobTitle;
  await test.step(`Open Candidates view for "${jobTitle}"`, async () => {
    await candidatesPage.searchAndOpenCandidates(jobTitle);
    await candidatesPage.assertApplicationsPageOpen(jobTitle);
  });
  const url = candidatesPage.getCandidatesPageUrl();
  const initialCount = await candidatesPage.getCandidateCount();
  return { url, initialCount, jobTitle };
}

// ══════════════════════════════════════════════════════════════════════════
//  TC_APP_001 — Resume upload flow (re-implemented end-to-end, plus
//  re-verification of the candidate opening the interview link)
//  Covers the "Resume upload flow" gap listed as 🟡 Partially covered.
// ══════════════════════════════════════════════════════════════════════════
test.describe('TC_APP_001 — Add candidate via Resume File Upload (Applications flow)', () => {

  test('Upload DOCX → Send Now → count +1 → Bulk Created toast', async ({
    page, browser, loggedInPage,
  }) => {
    const candidatesPage = new CandidatesPage(page);
    const docxPath       = path.resolve(PD, 'Advanced_DotNet_Resume_7.docx');
    const docxName       = 'Advanced_DotNet_Resume_7.docx';

    const { url, initialCount, jobTitle } = await openCandidates(candidatesPage);

    // ── upload + send now ──────────────────────────────────────────────
    await test.step(`Upload ${docxName} and send now`, async () => {
      await candidatesPage.addCandidateByResume(docxPath, 'now');
    });

    // ── verify ─────────────────────────────────────────────────────────
    await test.step('Verify count increased by 1', async () => {
      await candidatesPage.navigateToUrl(url);
      await candidatesPage.assertCandidateCount(initialCount + 1);
    });

    await test.step('Verify Bulk Created toast', async () => {
      await candidatesPage.assertBulkCreatedToast(1);
    });
  });

  test('Upload DOCX → Send Later → count +1 (no email check)', async ({
    page, loggedInPage,
  }) => {
    const candidatesPage = new CandidatesPage(page);
    const docxPath       = path.resolve(PD, 'Advanced_DotNet_Resume_7.docx');

    const { url, initialCount } = await openCandidates(candidatesPage);

    await test.step('Upload DOCX and send later', async () => {
      await candidatesPage.addCandidateByResume(docxPath, 'later');
    });

    await test.step('Verify count increased by 1', async () => {
      await candidatesPage.navigateToUrl(url);
      await candidatesPage.assertCandidateCount(initialCount + 1);
    });
  });
});

// ══════════════════════════════════════════════════════════════════════════
//  TC_APP_003 — Upload a PDF resume
// ══════════════════════════════════════════════════════════════════════════
test.describe('TC_APP_003 — Upload a PDF resume → candidate created', () => {

  test('Upload PDF → Send Now → count +1 and toast shown', async ({
    page, browser, loggedInPage,
  }) => {
    const candidatesPage = new CandidatesPage(page);
    const pdfPath        = path.resolve(PD, 'John_Smith_DotNet_Resume.pdf');
    const pdfName        = 'John_Smith_DotNet_Resume.pdf';

    const { url, initialCount } = await openCandidates(candidatesPage);

    await test.step(`Upload ${pdfName} (PDF) and send now`, async () => {
      await candidatesPage.addCandidateByFileUpload([pdfPath], 'now');
    });

    await test.step('Verify count increased by 1', async () => {
      await candidatesPage.navigateToUrl(url);
      await candidatesPage.assertCandidateCount(initialCount + 1);
    });

    await test.step('Verify Bulk Created toast', async () => {
      await candidatesPage.assertBulkCreatedToast(1);
    });
  });
});

// ══════════════════════════════════════════════════════════════════════════
//  TC_APP_004 — Upload a DOC (.doc) resume
//  Note: the fixture is a .docx; if the app distinguishes .doc vs .docx,
//  create a legacy .doc fixture and point this test at it.
// ══════════════════════════════════════════════════════════════════════════
test.describe('TC_APP_004 — Upload a DOC resume → candidate created', () => {

  test('Upload DOCX as stand-in for DOC flow → Send Now → count +1', async ({
    page, browser, loggedInPage,
  }) => {
    const candidatesPage = new CandidatesPage(page);
    // Use the same .docx fixture for now; swap to a true .doc when available.
    const docPath        = path.resolve(PD, 'John_Smith_DotNet_Resume.docx');

    const { url, initialCount } = await openCandidates(candidatesPage);

    await test.step('Upload DOC-style file and send now', async () => {
      await candidatesPage.addCandidateByFileUpload([docPath], 'now');
    });

    await test.step('Verify count increased by 1', async () => {
      await candidatesPage.navigateToUrl(url);
      await candidatesPage.assertCandidateCount(initialCount + 1);
    });
  });
});

// ══════════════════════════════════════════════════════════════════════════
//  TC_APP_005 — Multiple resume upload in one import
// ══════════════════════════════════════════════════════════════════════════
test.describe('TC_APP_005 — Upload multiple resume files in one import', () => {

  test('Upload 2 files (DOCX + PDF) → Send Now → count +2', async ({
    page, browser, loggedInPage,
  }) => {
    const candidatesPage = new CandidatesPage(page);
    const docxPath       = path.resolve(PD, 'Advanced_DotNet_Resume_7.docx');
    const pdfPath        = path.resolve(PD, 'John_Smith_DotNet_Resume.pdf');

    const { url, initialCount } = await openCandidates(candidatesPage);

    await test.step('Upload 2 resume files (DOCX + PDF) and send now', async () => {
      await candidatesPage.addCandidateByFileUpload([docxPath, pdfPath], 'now');
    });

    await test.step('Verify count increased by 2', async () => {
      await candidatesPage.navigateToUrl(url);
      await candidatesPage.assertCandidateCount(initialCount + 2);
    });

    await test.step('Verify Bulk Created toast for 2', async () => {
      await candidatesPage.assertBulkCreatedToast(2);
    });
  });
});

// ══════════════════════════════════════════════════════════════════════════
//  TC_APP_006 — Upload an unsupported file (not in the supported list)
//  Supported types per the app banner: PDF, DOC, DOCX, TXT, RTF.
//  We use a .zip (not in that list) so the "Unsupported files" banner
//  appears and no candidate is created.
// ══════════════════════════════════════════════════════════════════════════
test.describe('TC_APP_006 — Upload an unsupported (non-resume) file', () => {

  test('Upload .zip file → "Unsupported files" banner → count unchanged', async ({
    page, loggedInPage,
  }) => {
    const candidatesPage = new CandidatesPage(page);
    const zipPath        = path.resolve(PD, 'invalid_file.zip');

    const { url, initialCount } = await openCandidates(candidatesPage);

    await test.step('Upload unsupported .zip file through the full flow', async () => {
      try {
        await candidatesPage.addCandidateByFileUpload([zipPath], 'now');
      } catch (err) {
        console.log(`File-upload step threw (likely rejection): ${err.message}`);
      }
    });

    await test.step('Verify candidate count did NOT increase', async () => {
      await candidatesPage.navigateToUrl(url);
      const afterCount = await candidatesPage.getCandidateCount();
      expect(afterCount).toBe(initialCount,
        `Expected count to remain ${initialCount} but got ${afterCount}`);
    });

    await test.step('Capture any error message shown by the UI', async () => {
      const msg = await candidatesPage.getErrorMessage(8_000);
      if (msg) {
        console.log(`UI error message: ${msg}`);
      }
    });
  });
});
